// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "../node_modules/bs-platform/lib/es6/caml_option.js";

var iframe = document.querySelector("#iframe");

if (!(iframe == null)) {
  console.log(Caml_option.nullable_to_opt(iframe.contentWindow));
}

function maybeDoSomethingWithWindow($$window, param) {
  console.log($$window);
  
}

if (!(iframe == null)) {
  var $$window = Caml_option.some(iframe.contentWindow);
  console.log($$window);
}

var iframe$1 = (iframe == null) ? undefined : Caml_option.some(iframe);

export {
  iframe$1 as iframe,
  maybeDoSomethingWithWindow ,
  
}
/* iframe Not a pure module */
